led.enable(false)
basic.forever(function () {
    pins.digitalWritePin(DigitalPin.P2, 1)
    basic.pause(pins.analogReadPin(AnalogPin.P10) / 6)
    pins.digitalWritePin(DigitalPin.P2, 0)
    pins.digitalWritePin(DigitalPin.P3, 1)
    basic.pause(pins.analogReadPin(AnalogPin.P10) / 6)
    pins.digitalWritePin(DigitalPin.P3, 0)
    pins.digitalWritePin(DigitalPin.P4, 1)
    basic.pause(pins.analogReadPin(AnalogPin.P10) / 6)
    pins.digitalWritePin(DigitalPin.P4, 0)
    pins.digitalWritePin(DigitalPin.P5, 1)
    basic.pause(pins.analogReadPin(AnalogPin.P10) / 6)
    pins.digitalWritePin(DigitalPin.P5, 0)
    pins.digitalWritePin(DigitalPin.P6, 1)
    basic.pause(pins.analogReadPin(AnalogPin.P10) / 6)
    pins.digitalWritePin(DigitalPin.P6, 0)
    pins.digitalWritePin(DigitalPin.P7, 1)
    basic.pause(pins.analogReadPin(AnalogPin.P10) / 6)
    pins.digitalWritePin(DigitalPin.P7, 0)
    pins.digitalWritePin(DigitalPin.P8, 1)
    basic.pause(pins.analogReadPin(AnalogPin.P10) / 6)
    pins.digitalWritePin(DigitalPin.P8, 0)
    pins.digitalWritePin(DigitalPin.P9, 1)
    basic.pause(pins.analogReadPin(AnalogPin.P0) / 6)
    pins.digitalWritePin(DigitalPin.P9, 0)
    pins.digitalWritePin(DigitalPin.P11, 1)
    basic.pause(pins.analogReadPin(AnalogPin.P10) / 6)
    pins.digitalWritePin(DigitalPin.P11, 0)
})
basic.forever(function () {
    serial.writeLine("" + (pins.analogReadPin(AnalogPin.P10)))
})
